### ISSUE TITLE
Излишне негибкий код для всех заданий

### ISSUE THREAD

**Issue by NotAPattern** [VinogradovaD/Yandex_training_alg_2.0#2]
Всем привет. При просмотре репозитория столкнулся со негибкостью и нерасширяемостью кода в задачах.
Нельзя ли напихать куча абстрактных фабрик, пораждающих интерфейсы стратерий паттерна комманды?

В качестве примера прилагаю следующий репозиторий: https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition

PS.
Это просто рофл №2, не обращай особого внимания.

**Comment by VinogradovaD** [comment]
привет, спасибо за обратную связь :)  знаю, что код пока оставляет желать лучшего... можешь, пожалуйста, если не затруднит, поподробнее рассказать, в чем косяки ? мой тг - darinograd
